### PR TITLE
Add UKM, Malaysia

### PR DESCRIPTION
**Pull request by StevE-Ong**
I add http://www.ukm.my/jfg/en/

### CODE REVIEW

**Comment by PrometheusPi** [comment]
@StevE-Ong Thanks for adding UKM :+1: 
Could you merge your 5 commits into one? 

@psychocoderHPC For this repo, there seems to be no maintainers defined. Thus you have to merge as admin (or define maintainers).

**Comment by StevE-Ong** [comment]
Hi, is that OK? It is the first time to know commits can be merged.

**Comment by PrometheusPi** [comment]
Hi @StevE-Ong,
thanks for responding that quickly. Sadly now you created 12 commits from your 6 original ones. What I would like to have is that you squash/merge all 6 of your commits regarding UKM to a single commit. 

A description on how to do this can be found here:
for GitHub Desktop: https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/managing-commits/squashing-commits
on the terminal: https://www.git-tower.com/learn/git/faq/git-squash/

**Comment by StevE-Ong** [comment]
Hi, does it work now?

**Comment by PrometheusPi** [comment]
@StevE-Ong Thanks that's much better - could you still squash your two commit. Thus the diff tool remains get removed.

**Comment by StevE-Ong** [comment]
@PrometheusPi Sorry I dont get what you want.

**Comment by PrometheusPi** [comment]
~~@StevE-Ong I think you already solved the fixup/squash problem yourself - everything looks correct now with your last push.~~

Now I see even 4 commits. 


(My original message that I did not send in time:) 
@StevE-Ong What I meant was:
go to your `picongpu-communitymap` repository
run `git rebase -i HEAD~2`
now you get a list of the last 3 commit. The last two should be yours, just change from the last commit `pick` to `fixup`.

**Comment by PrometheusPi** [comment]
Thus `git rebase -i HEAD~4` and changing `pick` to `fixup` in the last 3 commits should solve your problem.

**Comment by StevE-Ong** [comment]
Is it OK now?

**Comment by PrometheusPi** [comment]
@StevE-Ong The current version is one commit (that's very good) but still contains fragments from your diff tool: (marked in red):

grafik

I will try to fix it.

**Comment by PrometheusPi** [comment]
@StevE-Ong I did want to force push to your main branch (you developed in the main branch) thus I opened a separate pull request. 
I will close this pull pull request now since it is superseded by #15.

**Pull request closed without merging**
